[package]
name = "testing"
version = "0.1.0"
authors = ["dowwie <dkcdkg@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2.0.0"
actix-rt = "1.0.0"
awc = { version = "1.0.1", features = ["rustls"] }
bytes = "0.5.4"
futures = "0.3.4"
